# Generated by Django 4.1.7 on 2023-04-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Sid', models.IntegerField(primary_key=True, serialize=False)),
                ('Sname', models.CharField(max_length=50)),
                ('Semail', models.EmailField(max_length=254)),
            ],
        ),
    ]
